# action.yml
name: 'Print Job Description'
description: 'Print GitHub Actions Job Description'
inputs:
  description-msg:  # id of input
    description: 'description message'
    required: true
    default: 'This is workflow job'
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-number }}
  # time: # id of output
  #   description: 'The time we greeted you'
runs:
  using: 'composite'
  steps:
    - run: echo Jobs Description ${{ inputs.description-msg }}
      shell: bash
    - id: random-number-generator
      run: echo "random-number=$(echo $RANDOM)" >> $GITHUB_OUTPUT
      shell: bash
  # using: 'docker'
  # image: 'Dockerfile'
  # args:
  #   - ${{ inputs.description-msg }}